export interface SearchEntry {
  title: string;
  href: string;
  section: string;
  headings: { id: string; text: string }[];
  keywords: string;
}

export const searchIndex: SearchEntry[] = [
  {
    title: "Introduction",
    href: "/introduction",
    section: "Welcome",
    headings: [
      { id: "what-is-frontier-pulse", text: "What is Frontier Pulse?" },
      { id: "the-problem", text: "The Problem" },
      { id: "the-solution", text: "The Solution" },
      { id: "key-features", text: "Key Features" },
      { id: "tech-stack", text: "Tech Stack" },
      { id: "design-philosophy", text: "Design Philosophy" },
      { id: "how-it-works", text: "How It Works" },
    ],
    keywords: "overview introduction what is frontier pulse eve frontier civilization health monitor trust living galaxy biometric hackathon sui blockchain design philosophy universe organism trust over activity on-chain truth how it works observe analyze record visualize",
  },
  {
    title: "Architecture",
    href: "/architecture",
    section: "Architecture",
    headings: [
      { id: "overview", text: "Overview" },
      { id: "data-paths", text: "Dual Data Paths" },
      { id: "on-chain-layer", text: "On-Chain Layer" },
      { id: "data-pipeline", text: "Data Pipeline" },
      { id: "deployed-contracts", text: "Deployed Contracts" },
    ],
    keywords: "architecture system design three tier oracle frontend smart contract data flow pipeline ptb programmable transaction blocks pulseregistry capability admin",
  },
  {
    title: "Quick Start",
    href: "/getting-started",
    section: "Quick Start",
    headings: [
      { id: "prerequisites", text: "Prerequisites" },
      { id: "installation", text: "Installation" },
      { id: "environment", text: "Environment Variables" },
      { id: "running-locally", text: "Running Locally" },
      { id: "deployment", text: "Deployment" },
    ],
    keywords: "install setup quick start prerequisites node npm git clone env environment variables running locally dev server oracle init",
  },
  {
    title: "Project Structure",
    href: "/project-structure",
    section: "Quick Start",
    headings: [
      { id: "overview", text: "Overview" },
      { id: "frontend", text: "Frontend" },
      { id: "oracle-backend", text: "Oracle Backend" },
      { id: "smart-contract", text: "Smart Contract" },
      { id: "lib-files", text: "Key Library Files" },
    ],
    keywords: "project structure files folders directory tree frontend oracle backend smart contract lib components api routes worldapi suireader store types",
  },
  {
    title: "Frontend",
    href: "/frontend",
    section: "Frontend",
    headings: [
      { id: "components", text: "Component Overview" },
      { id: "galaxy-canvas", text: "Galaxy Canvas" },
      { id: "heartbeat", text: "Dual Heartbeat EKG" },
      { id: "trust-compass", text: "Trust Compass" },
      { id: "archetypes", text: "Player Archetypes" },
      { id: "state", text: "State Management" },
    ],
    keywords: "frontend react next.js canvas galaxy map heartbeat ekg trust compass radar chart chi gauge zustand state management wallet watchlist components visualization",
  },
  {
    title: "Component Reference",
    href: "/components",
    section: "Frontend",
    headings: [
      { id: "visualization", text: "Visualization" },
      { id: "panels", text: "Panels & Navigation" },
      { id: "alerts", text: "Alerts & Transactions" },
      { id: "wallet", text: "Wallet & Onboarding" },
      { id: "state-management", text: "State Management" },
    ],
    keywords: "components galaxycanvas dualheartbeat chigauge trustcompass systempanel searchpalette alertbell walletmodal guidedtour watchlistpanel timelapse trustfilterbar subindexbars transactionhistory",
  },
  {
    title: "Oracle Backend",
    href: "/oracle",
    section: "Backend & Chain",
    headings: [
      { id: "overview", text: "Overview" },
      { id: "system-health", text: "System Health Scoring" },
      { id: "player-reputation", text: "Player Reputation" },
      { id: "chi-calculation", text: "Global CHI Calculation" },
      { id: "anomaly-detection", text: "Anomaly Detection" },
      { id: "sui-writer", text: "On-Chain Writer" },
    ],
    keywords: "oracle backend node.js cron scoring system health player reputation chi calculation anomaly detection sui writer ptb batch transaction pipeline world api",
  },
  {
    title: "Scoring Engine",
    href: "/scoring",
    section: "Backend & Chain",
    headings: [
      { id: "system-health", text: "System Health Scoring" },
      { id: "player-reputation", text: "Player Reputation" },
      { id: "chi", text: "Civilization Health Index" },
      { id: "anomaly-detection", text: "Anomaly Detection" },
      { id: "color-mapping", text: "Color Mapping" },
    ],
    keywords: "scoring algorithm formula system health activity trust player reputation reliability commerce diplomacy stewardship volatility chi civilization health index economic security growth connectivity social cohesion anomaly detection color trust spectrum archetype",
  },
  {
    title: "Smart Contract",
    href: "/smart-contract",
    section: "Backend & Chain",
    headings: [
      { id: "overview", text: "Overview" },
      { id: "core-structs", text: "Core Structs" },
      { id: "formulas", text: "On-Chain Formulas" },
      { id: "write-functions", text: "Oracle Write Functions" },
      { id: "read-functions", text: "Public Read Functions" },
      { id: "endorsements", text: "System Endorsements" },
    ],
    keywords: "smart contract sui move pulseregistry playerreputation systemhealth civilizationhealthindex admincap oraclecap endorsement struct event update read write",
  },
  {
    title: "API Reference",
    href: "/api-reference",
    section: "API & Deploy",
    headings: [
      { id: "universe", text: "Universe" },
      { id: "chi", text: "Civilization Health Index" },
      { id: "system", text: "System Detail" },
      { id: "player", text: "Player Reputation" },
      { id: "alerts", text: "Anomaly Alerts" },
      { id: "transactions", text: "Transaction Log" },
      { id: "pulse-card", text: "Pulse Card" },
      { id: "data-sources", text: "Data Sources" },
    ],
    keywords: "api reference endpoint route get universe chi system player alerts transactions pulse card svg rest json response",
  },
  {
    title: "Data Sources",
    href: "/data-sources",
    section: "Architecture",
    headings: [
      { id: "world-api", text: "EVE Frontier World API" },
      { id: "sui-blockchain", text: "Sui Blockchain" },
      { id: "data-priority", text: "Data Priority Chain" },
      { id: "caching", text: "Caching & Refresh Rates" },
      { id: "external-links", text: "External Resources" },
    ],
    keywords: "data sources world api solarsystems smartassemblies killmails sui blockchain json-rpc getobject query transaction blocks pagination normalization coordinates cache ttl refresh",
  },
  {
    title: "Deployment",
    href: "/deployment",
    section: "API & Deploy",
    headings: [
      { id: "frontend", text: "Frontend (Vercel)" },
      { id: "oracle", text: "Oracle Backend" },
      { id: "smart-contract", text: "Smart Contract" },
      { id: "contract-ids", text: "Deployed Contract IDs" },
      { id: "troubleshooting", text: "Troubleshooting" },
    ],
    keywords: "deployment deploy vercel railway production oracle setup env private key sui move publish contract ids troubleshooting oraclecap gas balance",
  },
  {
    title: "Glossary",
    href: "/glossary",
    section: "Resources",
    headings: [
      { id: "core-concepts", text: "Core Concepts" },
      { id: "scoring-health", text: "Scoring & Health" },
      { id: "player-archetypes", text: "Player Archetypes" },
      { id: "anomaly-types", text: "Anomaly Types" },
      { id: "technical-terms", text: "Technical Terms" },
      { id: "eve-frontier-terms", text: "EVE Frontier Terms" },
    ],
    keywords: "glossary definitions terms chi civilization health index agora engine pulse layer trust compass heartbeat activity level trust level local chi sub-index diagnosis archetype civilization builder trusted trader diplomat warlord wildcard newcomer blackout trust collapse combat hotspot trade spike pulseregistry oraclecap admincap ptb programmable transaction block deterministic fallback endorsement solar system smart assembly killmail gate link world api",
  },
  {
    title: "FAQ",
    href: "/faq",
    section: "Resources",
    headings: [
      { id: "general", text: "General" },
      { id: "technical", text: "Technical" },
      { id: "trust-scoring", text: "Trust & Scoring" },
      { id: "wallet", text: "Wallet & On-Chain" },
    ],
    keywords: "faq frequently asked questions what is frontier pulse track external tools eve frontier wallet sui blockchain oracle cron 60fps canvas trust calculation archetype gaming anomaly alert endorsement dapp-kit suiet ethos nightly martian",
  },
  {
    title: "Changelog",
    href: "/changelog",
    section: "Resources",
    headings: [
      { id: "changelog", text: "Changelog" },
      { id: "roadmap", text: "Roadmap" },
    ],
    keywords: "changelog roadmap version history release milestones v1.0 hackathon submission on-chain integration trust intelligence galaxy foundation mainnet websocket alliance mobile ai prediction governance widgets",
  },
  {
    title: "Team & Links",
    href: "/team",
    section: "Resources",
    headings: [
      { id: "team", text: "Our Team" },
      { id: "links", text: "Project Links" },
    ],
    keywords: "team members developer sanjaya secondio ezra github demo video dapp link hackathon contact email",
  },
];
